---
application:
  name: "node-docker"
  project: "project-bagaskara"
  organization: "QoveryCommunity"
routers:
- name: "main-node-docker"
  routes:
  - application_name: "node-docker"
    paths:
    - "/*"
